### PR TITLE
Basic workgraph tests

### PR DESCRIPTION
**Pull request by HansKristian-Work**
This needs SDK 613 headers and latest DXC version.

These are basic "hello world" tests. There is no data passing between nodes here.

WARP has some bugs with multiple GPU input nodes.
AMD driver hangs GPU with CPU inputs + 0 stride. Most likely they screw up memory allocation requirements for that CPU data.

Otherwise, the tests passed on RX 7600 with the adrenalin driver now.

### CODE REVIEW

**Comment by oscarbg** [comment]
Do you want/need testing on a NV Ada card?

**Comment by HansKristian-Work** [comment]
Tests pass as-is on RTX 4070.

**Comment by doitsujin** [comment]
Looks like there are some unused variable warnings from the new tests, other than that LGTM.

**Comment by HansKristian-Work** [comment]
Also fixed the annoying so_strides warning nit while I was at it.

**Pull request merged**
