### PR TITLE
vkd3d: Init hashmap in vkd3d_create_image_resource

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
Closes: #353
Signed-off-by: Joshua Ashton <joshua@froggi.es>

### CODE REVIEW

**Comment by doitsujin** [comment]
Do we want to keep the native demos around even though parts of the API implementation don't even work with native builds?

**Comment by HansKristian-Work** [comment]
The extra maintenance to have them is fairly minimal, and it's useful to sanity check with them. The APIs that don't work in native builds are quite obscure to be fair ...

**Comment by Joshua-Ashton** [comment]
I think we should keep the native demos around because afaik we aren't planning to (and imo, shouldn't) deprecate/toss out the ability to compile native.

It's a good sanity check also.

**Review by HansKristian-Work — APPROVED** [review]
LGTM.

**Pull request merged**
