### PR TITLE
meson: Target native d3d12 for Windows test binaries.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Maybe only do this for ``enable_standalone_d3d12`` = True?

**Comment by HansKristian-Work** [comment]
It actually works out nicely without standalone_d3d12 since it ends up linking against vkd3d-utils in that case.

**Comment by HansKristian-Work** [comment]
actually, need to hoist out the conditional path in enable_extras ...

**Comment by Joshua-Ashton** [comment]
> It actually works out nicely without standalone_d3d12 since it ends up linking against vkd3d-utils in that case.

I meant when building for Windows without standalone_d3d12.

I would add the DXGI always if the platform is Windows and substitute vkd3d and vkd3d_utils for lib_d3d12 depending on the standalone_d3d12 option.

**Comment by HansKristian-Work** [comment]
Actually, I think I need to make use of the VKD3D_FORCE_UTILS_WRAPPER thingy to make this work since we cannot mix and match DXGI with utils wrapper, I'll close the PR for now.

**Pull request closed without merging**
