### PR TITLE
meson: Update to version 2.3.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Did a fairly wide sweep over Big Navi and Ampere and no obvious issues on my end.

**Review by Joshua-Ashton — APPROVED** [review]
LGTM, can we fix that singular dxil-spirv warning before release though?

**Comment by Joshua-Ashton** [comment]
Tested HZD on Radeon VII

**Comment by HansKristian-Work** [comment]
> LGTM, can we fix that singular dxil-spirv warning before release though?

Which warning?

**Review by doitsujin — APPROVED** [review]

**Comment by Joshua-Ashton** [comment]
Its on the CI

**Pull request merged**
