### PR TITLE
Implement VK_NV_device_generated_commands_compute

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Simple implementation. Just needs to consider that COMPUTE tokens can also be used as well and need to use the correct bind_points for pipeline layouts, etc.

VKD3D_TEST_FILTER=multi_dispatch passes on RADV with MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24275

Fails on latest NV beta with:

```
d3d12:608: Driver name: NVIDIA, driver info: 525.47.34.
2cac:info:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
2cac:info:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
2cac:info:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.019 ms.
2cac:info:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.023 ms.
2cac:info:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.003 ms.
2cac:info:vkd3d_pipeline_library_disk_cache_initial_setup: Cannot load existing on-disk cache due to driver version mismatch.
2cac:info:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
d3d12: ======== test_execute_indirect_multi_dispatch begin ========
2ca0:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
2ca0:info:vkd3d_instance_init: vkd3d-proton - build: bef79dabe5cc2d9.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x20.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x40.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x100.
2ca0:info:vkd3d_memory_info_upload_hvv_memory_properties: Topology: No more than 1 device local heap, assuming ReBAR-style access. Using DEVICE_LOCAL | HOST_COHERENT for UPLOAD.
2ca0:info:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x10.
2ca0:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_EXT_mutable_descriptor_type.
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
2ca0:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 4416, may be inaccurate.
2ca0:info:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
2cb4:info:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
2cb4:info:vkd3d_pipeline_library_disk_cache_merge: No write cache exists. No need to merge any disk caches.
2cb4:info:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.013 ms.
2cb4:info:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.013 ms.
2cb4:info:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.002 ms.
2cb4:info:vkd3d_pipeline_library_disk_cache_initial_setup: Cannot load existing on-disk cache due to driver version mismatch.
2cb4:info:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
2cb4:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
d3d12: ======== test_execute_indirect_multi_dispatch end ==========
d3d12: ======== test_execute_indirect_multi_dispatch_root_constants begin ========
2ca0:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
2ca0:info:vkd3d_instance_init: vkd3d-proton - build: bef79dabe5cc2d9.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x20.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x40.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x100.
2ca0:info:vkd3d_memory_info_upload_hvv_memory_properties: Topology: No more than 1 device local heap, assuming ReBAR-style access. Using DEVICE_LOCAL | HOST_COHERENT for UPLOAD.
2ca0:info:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x10.
2ca0:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_EXT_mutable_descriptor_type.
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
2ca0:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 4416, may be inaccurate.
2ca0:info:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
2cbe:info:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
2cbe:info:vkd3d_pipeline_library_disk_cache_merge: Merging disk caches.
2cbe:info:vkd3d_pipeline_library_disk_cache_merge: Read-only cache is out of date, discarding it.
2cbe:info:vkd3d_pipeline_library_disk_cache_merge: Successfully promoted write cache to read cache.
2cbe:info:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.113 ms.
2cbe:info:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.007 ms.
2cbe:info:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.004 ms.
2cbe:info:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
2cbe:info:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
test_execute_indirect_multi_dispatch_root_constants:1884: Todo succeeded: Failed to create command signature, hr #0.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 1: Expected 969370, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 2: Expected 138007, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 3: Expected 861955, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 4: Expected 138007, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 5: Expected 888658, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 6: Expected 559252, got 7.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 7: Expected 1029832, got 7.
d3d12: ======== test_execute_indirect_multi_dispatch_root_constants end ==========
d3d12: ======== test_execute_indirect_multi_dispatch_root_descriptors begin ========
2ca0:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.9.0.
2ca0:info:vkd3d_instance_init: vkd3d-proton - build: bef79dabe5cc2d9.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x20.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x40.
2ca0:fixme:debug_vk_queue_flags: Unrecognized flag(s) 0x100.
2ca0:info:vkd3d_memory_info_upload_hvv_memory_properties: Topology: No more than 1 device local heap, assuming ReBAR-style access. Using DEVICE_LOCAL | HOST_COHERENT for UPLOAD.
2ca0:info:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x10.
2ca0:info:vkd3d_bindless_state_get_bindless_flags: Device supports VK_EXT_mutable_descriptor_type.
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:vkd3d_bindless_state_add_binding: Device supports VK_EXT_descriptor_buffer!
2ca0:info:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
2ca0:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 4416, may be inaccurate.
2ca0:info:vkd3d_pipeline_library_init_disk_cache: Attempting to load disk cache from: vkd3d-proton.cache.
2cc8:info:vkd3d_pipeline_library_disk_thread_main: Performing async setup of stream archive ...
2cc8:info:vkd3d_pipeline_library_disk_cache_merge: Merging disk caches.
2cc8:info:vkd3d_pipeline_library_disk_cache_merge: Done merging shader caches, existing entries: 1, new entries: 1.
2cc8:info:vkd3d_pipeline_library_disk_cache_merge: Successfully replaced shader cache with merged cache.
2cc8:info:vkd3d_pipeline_library_disk_cache_initial_setup: Merging pipeline libraries took 0.163 ms.
2cc8:info:vkd3d_pipeline_library_disk_cache_initial_setup: Mapping read-only cache took 0.010 ms.
2cc8:info:vkd3d_pipeline_library_disk_cache_initial_setup: Parsing stream archive took 0.005 ms.
2cc8:info:vkd3d_pipeline_library_disk_thread_main: Done performing async setup of stream archive.
test_execute_indirect_multi_dispatch_root_descriptors:1714: Todo succeeded: Failed to create command signature, hr #0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 0: Expected 24, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 1: Expected 420, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 2: Expected 1440, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 3: Expected 1188, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 4: Expected 4368, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 5: Expected 13650, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 6: Expected 19584, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 7: Expected 11970, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 8: Expected 96, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 9: Expected 840, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 10: Expected 1440, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 11: Expected 792, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 12: Expected 1092, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 13: Expected 2730, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 14: Expected 4896, got 0.
test_execute_indirect_multi_dispatch_root_descriptors:1779: Test failed: Value 15: Expected 2394, got 0.
d3d12: ======== test_execute_indirect_multi_dispatch_root_descriptors end ==========
d3d12: 81 tests executed (24 failures, 2 successful todo, 0 skipped, 0 todo, 0 bugs).
```

### CODE REVIEW

**Review by doitsujin — APPROVED** [review]
Looks simple enough, but we'll probably want the nvidia failures to be looked at.

**Comment by HansKristian-Work** [comment]
Merging this as-is might regress Halo Infinite on NV, so can hold off merging for the time being.

**Comment by vkushwaha-nv** [comment]
I see 2 spec violations

1. compute pipeline used has no associated buffer device address. Spec:
If a compute pipeline is going to be used in Device-Generated Commands, then that pipeline’s associated metadata must be saved at a specified buffer device address for later use in indirect command generation. The buffer device address must be specified at the time of compute pipeline creation with VkComputePipelineIndirectBufferInfoNV structure in the pNext chain of VkComputePipelineCreateInfo.


2. For the compute pipeline specified in vkCmdExecuteGeneratedCommandsNV::pGeneratedCommandsInfo, vkCmdUpdatePipelineIndirectBuffer has not been called. Spec:
If pipelineBindPoint is of type VK_PIPELINE_BIND_POINT_COMPUTE, then vkCmdUpdatePipelineIndirectBuffer must have been called on that pipeline to save its metadata to a device address

**Comment by HansKristian-Work** [comment]
@vkushwaha-nv

> I see 2 spec violations:
> 
>     1. Compute pipeline used has no associated buffer device address, spec:
>        If a compute pipeline is going to be used in Device-Generated Commands, then that pipeline’s associated metadata must be saved at a specified buffer device address for later use in indirect command generation. The buffer device address must be specified at the time of compute pipeline creation with VkComputePipelineIndirectBufferInfoNV structure in the pNext chain of VkComputePipelineCreateInfo.
> 
>     2. pipeline specified in vkCmdExecuteGeneratedCommandsNV::pGeneratedCommandsInfo must have had vkCmdUpdatePipelineIndirectBuffer called on it. spec:
>        If pipelineBindPoint is of type VK_PIPELINE_BIND_POINT_COMPUTE, then vkCmdUpdatePipelineIndirectBuffer must have been called on that pipeline to save its metadata to a device address

We don't use INDIRECT_BINDABLE, so none of these should be required. I think there's some confusion in the spec language here, since there is:

```
VUID-VkComputePipelineCreateInfo-flags-09008
If flags includes VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV, then the pNext chain must include a pointer to a valid instance of [VkComputePipelineIndirectBufferInfoNV](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkComputePipelineIndirectBufferInfoNV) specifying the address where the pipeline’s metadata will be saved
```

**Comment by HansKristian-Work** [comment]
> Is providing a buffer and a flag an issue? If it is for compatibility reasons, then we might have to think of another approach.

Yes, this effectively makes it unimplementable. D3D12 does not require up-front knowledge about whether or not a pipeline will be used in ExecuteIndirect. AFAIK, the metadata buffer was mostly only relevant to make pipeline capture replay work.

It's also invalid for us to use the metadata buffer:

> VUID-VkComputePipelineCreateInfo-flags-09007
If flags includes VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV, then the [VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV::deviceGeneratedComputePipelines](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-deviceGeneratedComputePipelines) feature must be enabled

But that's an optional feature that e.g. RADV does not implement.

**Comment by vkushwaha-nv** [comment]
Ack. Checking what can be done.

**Comment by vkushwaha-nv** [comment]
I have an internal change to get that working. However, I see the test either crashes or fails:
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 7.

I think this is the shader it is trying to execute:

```
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(buffer_reference) buffer _7;
layout(buffer_reference, buffer_reference_align = 4, std430) buffer _7
{
    uint _m0[];
};
layout(push_constant, std430) uniform push_cb
{
    uvec2 va0;
    float cb0_0;
    float cb0_1;
    float cb0_2;
    float cb0_3;
} _16;

void main()
{
    vec4 r0;
    r0.x = uintBitsToFloat(floatBitsToUint(_16.cb0_1) | floatBitsToUint(_16.cb0_0));
    r0.x = uintBitsToFloat(floatBitsToUint(r0.x) | floatBitsToUint(_16.cb0_2));
    r0.x = uintBitsToFloat(floatBitsToUint(r0.x) | floatBitsToUint(_16.cb0_3));
    uint _57 = uint(0) * 1u;
    uint _65 = atomicAdd(_7(_16.va0)._m0[_57 + (uint(0) >> 2u)], floatBitsToUint(r0.x));
}
```

Push constants are specified at offset 0, with stride 16
Dispatch params are specified at offset 4, with stride 16

Contents of stream buffer are:
0000000d 0000000a 00000014 0000001e 
0000000e 0000000b 00000015 0000001f 
0000000f 00000000 00000016 00000020 
00000010 0000000d 00000017 00000000 
00000011 0000000a 00000014 0000001e 
00000012 0000000b 00000015 0000001f 
00000013 0000000c 00000016 00000020 
00000014 0000000d 00000017 00000021 
00000015 0000000a 00000014 0000001e 
00000016 0000000b 00000015 0000001f 
00000017 0000000c 00000016 00000020 
00000018 0000000d 00000017 00000021 
00000019 0000000a 00000014 0000001e 
0000001a 0000000b 00000015 0000001f 
0000001b 0000000c 00000016 00000020 
0000001c 0000000d 00000017 00000021 

VkIndirectCommandsLayoutTokenNV::pushconstantOffset is specified 16, and VkIndirectCommandsLayoutTokenNV::pushconstantSize is 4.

So, only "float cb0_2" is getting the values through DGCC. I assume the remaining are provided with regular vkCmdPushConstants? 
The values "float cb0_2" is receiving would be 0xd, 0xe, 0xf, 0x10 etc for each successive dispatch.

The groupCountX,Y,Z values are going to be [0xa, 0x14, 0x1e], [0xb, 0x15, 0x1f], [0x0, 0x16, 0x20] etc for successive dispatch. The fact that one of those values is 0, suggests the input to DGCC is wrong.

Can you check if this is what the test is expecting?

**Comment by HansKristian-Work** [comment]
@vkushwaha-nv In the first test iteration, the expected result is 90007 because there is first one dispatch that reads these values:

`13, 10, 20, 30, /* root constant u32 + dispatch group counts */`

float cb0_2 should become 13. The shader does InterlockedAdd with cb0_0 | cb0_1 | cb0_2 | cb0_3 which evaluates to 1 | 2 | 13 | 4 == 15. The push constants which are unset by DGCC are set by vkCmdPushConstants before.

Number of workgroups is (10, 20, 30) and workgroup size is (1, 1, 1), so there's 6000 invocations. 6000 * 15 = 90000. Then, there's a single non-indirect dispatch workgroup which should increment by 7, making the result 90007.

**Comment by vkushwaha-nv** [comment]
I have a change that should fix this, but we still need to make sure the input stream buffer does not have zeros here:

0000000d 0000000a 00000014 0000001e
0000000e 0000000b 00000015 0000001f
0000000f **00000000** 00000016 00000020
00000010 0000000d 00000017 **00000000**

Could a barrier be missing for that update?

**Comment by HansKristian-Work** [comment]
> I have a change that should fix this, but we still need to make sure the input stream buffer does not have zeros here:
> 
> 0000000d 0000000a 00000014 0000001e 0000000e 0000000b 00000015 0000001f 0000000f **00000000** 00000016 00000020 00000010 0000000d 00000017 **00000000**
> 
> Could a barrier be missing for that update?

This is intentional. It's testing that the implementation can handle empty dispatches.

**Comment by HansKristian-Work** [comment]
@vkushwaha-nv Have to merge this now. For now, I added a workaround which disables the extension on NV. For testing, this can be bypassed with `VKD3D_CONFIG=skip_driver_workarounds` and the workaround will be removed when a fix lands in a beta driver.

**Comment by vkushwaha-nv** [comment]
I have fixed this in our side and a release should be out soon. 

I am still seeing some problems with your test though.

1.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 1059370.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 1: Expected 969370, got 7.

Looks like the sum of expected and results are the same. I wonder if you are missing a barrier before checking the result between launches.

2.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 5: Expected 888658, got 1574839.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 7: Expected 1029832, got 1215832.

Here I noticed that you are providing the count Value with a count buffer and the value exceeds VkGeneratedCommandsMemoryRequirementsInfoNV::maxSequencesCount  (e.g using 8 and 6 respectively in VkGeneratedCommandsInfoNV::sequencesCountBuffer, whereas the VkGeneratedCommandsMemoryRequirementsInfoNV::maxSequencesCount was 5)

Also, did the math for iteration 5 with 8 sequences. The expected output should be 7 + 23*7161 + 23*8448 + 23*9867+ 23*6000+ 23*7161+ 23*8448+ 31*9867+ 31*6000 = 1574839
(based on input sequence:
00000012 0000000b 00000015 0000001f
00000013 0000000c 00000016 00000020
00000014 0000000d 00000017 00000021
00000015 0000000a 00000014 0000001e
00000016 0000000b 00000015 0000001f
00000017 0000000c 00000016 00000020
00000018 0000000d 00000017 00000021
00000019 0000000a 00000014 0000001e)


3. For the test_execute_indirect_multi_dispatch_root_descriptors variant, I see the same issue, i.e. the count Value in VkGeneratedCommandsInfoNV::sequencesCountBuffer exceeds VkGeneratedCommandsMemoryRequirementsInfoNV::maxSequencesCount for iteration 5 and 7.

**Comment by HansKristian-Work** [comment]
> test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 5: Expected 888658, got 1574839.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 7: Expected 1029832, got 1215832.

In multi-indirect scenarios, the maxCommandCount serves as an upper bound that clamps the input sequence count. This is the case for graphics DGC, D3D12 ExecuteIndirect and Vulkan MultiDrawIndirect. The bug here is mostly likely the clamp value not being taken into account.

> test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 1059370.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 1: Expected 969370, got 7.

I'll look at it.

**Comment by HansKristian-Work** [comment]
> test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 1059370.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 1: Expected 969370, got 7.

This cannot be a sync issue, the test will push a pointer for each separate test iteration where an atomic is incremented.

```
        ID3D12GraphicsCommandList_SetComputeRootUnorderedAccessView(context.list, 0,
            ID3D12Resource_GetGPUVirtualAddress(output) + 4 * test_index);
```

This should result in the pattern of:

```
vkCmdPushConstant() to update the atomic pointer
vkCmdExecuteCommands()
```

I cannot see how this would be a sync issue on our end, if iteration 1 somehow sees the pointer from iteration 0.

**Comment by vkushwaha-nv** [comment]
Thanks, clamping it to max fixes the issues. However, the below issue still remains:

test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 0: Expected 90007, got 1059370.
test_execute_indirect_multi_dispatch_root_constants:1954: Test failed: Iteration 1: Expected 969370, got 7.

Can you explain how the value is written in the buffer or add the shader here? Perhaps the descriptor buffers offsets overlap between instances 0 and 1?

Here is the shader I see:

#version 450
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference_uvec2 : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference) buffer _7;
layout(buffer_reference, buffer_reference_align = 4, std430) buffer _7
{
    uint _m0[];
};

layout(push_constant, std430) uniform push_cb
{
    uvec2 va0;
} _13;

void main()
{
    uint _22 = uint(0) * 1u;
    uint _28 = atomicAdd(_7(_13.va0)._m0[_22 + (uint(0) >> 2u)], 1u);
}
I don't understand what "_7(_13.va0)._m0[0]" means below:
atomicAdd(_7(_13.va0)._m0[0], 1u);

**Comment by HansKristian-Work** [comment]
The shader is casting an address (uvec2 va0) to BDA and then does atomicAdd. Instance 1 should have an offset that is 4 bytes away from Instance 0, so there cannot possibly be cross talk here. Instance 0 should never touch memory that instance 1 is touching.

My theory is that there is a race condition somewhere in your impl where push constants aren't updated when they're supposed to.

**Comment by HansKristian-Work** [comment]
What happens if you only execute iteration 0?

**Comment by vkushwaha-nv** [comment]
Looks like a push constant caching issue indeed. Thanks! Adding a fix.

**Pull request merged**
