### PR TITLE
include: Implement 64-bit and pointer atomics 

### PR DESCRIPTION
**Pull request by Joshua-Ashton**

### CODE REVIEW

**Review by doitsujin — APPROVED** [review]
Looks good to me (albeit a bit ugly with the MSVC hacks), but probably won't hurt if @HansKristian-Work could take a look next week as well.

**Comment by doitsujin** [comment]
Ah, actually - we'll need compare and swap as well, which is currently completely missing.

**Comment by Joshua-Ashton** [comment]
Added compare and swap.

**Review by HansKristian-Work — APPROVED** [review]
LGTM.

**Pull request merged**
