### PR TITLE
Remove use of ms_abi for native builds

### PR DESCRIPTION
**Pull request by expipiplus1**
This brings the native headers in line with the official DirectX headers and dxvk

### CODE REVIEW

**Comment by expipiplus1** [comment]
Closes https://github.com/HansKristian-Work/vkd3d-proton/issues/1511

**Comment by expipiplus1** [comment]
I still need to check if this requires defining `WIDL_EXPLICIT_AGGREGATE_RETURNS`

**Comment by HansKristian-Work** [comment]
The vtables are implemented assuming the explicit aggregate returns fwiw, so I don't think we should mess around with that. Just changing the calling convention should be good enough I think.

**Comment by HansKristian-Work** [comment]
Also, do you consent to this contribution being relicensed to MIT?

**Comment by expipiplus1** [comment]
> Also, do you consent to this contribution being relicensed to MIT?

Sure, that's fine

**Comment by expipiplus1** [comment]
> The vtables are implemented assuming the explicit aggregate returns fwiw, so I don't think we should mess around with that. Just changing the calling convention should be good enough I think. The last comment suggets the PR isn't ready for review, so I'll wait until notified.

Ah, perhaps this is an orthogonal issue caused by me using WIDL 8.0 then... As one would expect with how the vtables are implemented, it is necessary to define `WIDL_EXPLICIT_AGGREGATE_RETURNS` before including `vkd3d_dx12.h`.

I'm happy for this to be merged as is, and sort out this aggregate return issue elsewhere.

For quick reference, this is what WIDL 8.0 generates:

```C++
ID3D12Heap : public ID3D12Pageable
{
#ifdef WIDL_EXPLICIT_AGGREGATE_RETURNS
    virtual D3D12_HEAP_DESC* STDMETHODCALLTYPE GetDesc(
        D3D12_HEAP_DESC *__ret) = 0;
    D3D12_HEAP_DESC STDMETHODCALLTYPE GetDesc(
        )
    {
        D3D12_HEAP_DESC __ret;
        return *GetDesc(&__ret);
    }
#else
    virtual D3D12_HEAP_DESC STDMETHODCALLTYPE GetDesc(
        ) = 0;
#endif
};
```

I think the fix here would be to add `-DWIDL_EXPLICIT_AGGREGATE_RETURNS` to the WIDL invocation.

**Comment by HansKristian-Work** [comment]
```
cpp_quote("#ifndef WIDL_EXPLICIT_AGGREGATE_RETURNS")
cpp_quote("#define WIDL_EXPLICIT_AGGREGATE_RETURNS")
```
That seems fine to me.

**Comment by expipiplus1** [comment]
I implemented it with push/pop_macro so as to not pollute the includer's macro state. I believe that this is supported by gcc, clang and msvc

**Review by HansKristian-Work — APPROVED** [review]
LGTM, thanks.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
