### PR TITLE
dxil-spirv: Update submodule.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Improves some behavior for strict helper lanes in subgroup ops. It turns out that RADV and NV can emit helper lanes even it makes no sense for the shader to do so, so be conservative and always consider helper lanes potentially active in fragment shaders.

Also consider helper lane behavior in SPV_NV_subgroup_partitioned.

This affects various games, so this needs some smoke testing on various games:

- F1 2021
- Halo Infinite
- Monster Hunter Rise
- RE2
- RE8
- CP77
- Deathloop
- Dragons Dogma 2
- RE4
- SF6
- Starfield
- The Last of Us Part 1

Should be tested on NV and RADV.

### CODE REVIEW

**Comment by runar-work** [comment]
No issues related to this MR so far. Tested F1 2021 on 6.9.1-arch1-1, RX 7600 with RADV 24.0.7.

On RTX 3070 with 555.42.02:

- F1 2021
- Cyberpunk 2077
- Monster Hunter Rise
- Resident Evil 2
- Resident Evil Village

**Comment by runar-work** [comment]
Also on 555.42.02:

- Resident Evil 4
- Deathloop
- Halo Infinite
- Street Fighter 6

No issues apart from some glitchy shadow rendering in Deathloop, but that seems to be driver specific, unrelated to this MR.

**Comment by runar-work** [comment]
I didn't have any issues when I tested TLOU1 this time, still on RTX 3070 and 555.42.02. Tested for about half an hour in a few different locations with various graphics settings, like outside the capitol building and in the slums where I know I've had a hang in the past. Maybe it was just chance, some difference in graphics settings, or maybe it's worse on Ada.

**Comment by shelterx** [comment]
@runar-work Might be an Ada only issue, I don't know. I know for a fact I did not experience any issues with my 3060 when I had that. But I HAVE played TLOU with the 4070 without crashes too... I once thought it was fixed, then the second time I started it took ~1 minute then the game froze and I got XID 109.

**Comment by runar-work** [comment]
I tried to test Starfield, but the game won't launch with this MR and 555.42.02. Seems like it fails in a shader compile thread. I also launched it on my iGPU with similar results. Here's a proton log from the RTX 3070 with +vulkan and trace debug level: [steam-1716740_launch_fail_MR_trace.log](https://github.com/HansKristian-Work/vkd3d-proton/files/15437185/steam-1716740_launch_fail_MR_trace.log)

I also tested Dragon's Dogma 2, which seemed to be equally glitchy with this MR and without it. I did get a Xid 109 with the MR right after the medusa fight in the beginning, but wasn't able to reproduce that afterwards. I tried to vary the graphics settings a bit, but I probably should've gone a bit lower to see if the glitchiness improved (occasional vertex explosions and such).

**Comment by HansKristian-Work** [comment]
@runar-work Starfield should work now on updated PR.

**Comment by runar-work** [comment]
Yeah, Starfield works fine now. Tested for a little while without issues.

**Comment by HansKristian-Work** [comment]
Enough test coverage now, so going ahead.

**Pull request merged**
