### PR TITLE
vkd3d: Add option to curb memory PSO cache bloat.

### PR DESCRIPTION
**Pull request by HansKristian-Work**

### CODE REVIEW

**Review by doitsujin — APPROVED** [review]

**Comment by K0bin** [comment]
Can ANV even run the game in the first place?

**Comment by renatopereyra** [comment]
I don't have an Intel card to test. I just thought that RADV and ANV would be affected similarly here and I didn't see a reason to explicitly leave ANV out.

**Comment by mbriar** [comment]
Games like this that require feature level 12_0 don't run on anv anyways due to missing features and need manual feature level overrides to even try to launch them.

**Comment by renatopereyra** [comment]
ANV will support this feature at level at some point and then hit this bug in all likelihood since it shares much of the shader cache code with RADV. I thought it would save time overall to do both of them together for things that are known to be common between them.

**Comment by Blisto91** [comment]
I don't know much about ANV specifically bit at least for RADV this is intended to be a temporary work around until work in RADV has made a better solution. (afaiu)

**Pull request merged**
