### PR TITLE
vkd3d: Remove Cyberpunk 2077 shader quirks

### PR DESCRIPTION
**Pull request by pixelcluster**
The bug has been fixed game-side. Yay!

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Is it worth removing these? If they have new shaders, then this should only trigger on the older versions?

**Comment by pixelcluster** [comment]
Yeah, I don't think the quirks get triggered anymore. But do we really want to keep essentially dead workarounds for outdated versions of the game? I don't think we expect any users to run game versions 2.0-2.11 anymore (the issue started appearing in 2.0 and has been fixed in 2.12 IIRC).

Some people might still use the 1.x branch from before Phantom Liberty released because 2.0 raised system requirements, but the issue doesn't appear there either.

**Comment by Joshua-Ashton** [comment]
Yeah, mainly just thinking of modders/speedrunners given that game has a big scene there.

**Comment by shelterx** [comment]
My thought is just why not just add a comment on what versions those workarounds are for and saying it's fixed from version x.x. instead.

**Comment by HansKristian-Work** [comment]
> Yeah, mainly just thinking of modders/speedrunners given that game has a big scene there.

Is there any evidence speedrunners are targeting >= 2.0 && <= 2.11? Why would they play with DXR on? And if they lock to specific versions, any reason why they cannot use specific vkd3d-protons versions as well?

**Comment by doitsujin** [comment]
Agree that we should remove the workaround if this has been fixed in game.

**Review by HansKristian-Work — APPROVED** [review]

**Comment by HansKristian-Work** [comment]
Ok, let's do that then.

**Pull request merged**
