### PR TITLE
gitignore: Ignore additional build artifacts

### PR DESCRIPTION
**Pull request by FaithLV**
This PR adds `.dll` and `builddir/*` to .gitignore

Signed-off-by: Valters <valters.tomsons@protonmail.com>

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Why `builddir`? Why are you calling your build folder that when there are plenty of other options in the .gitignore already?

All the DLLs should also be built inside the meson build folder so I don't see why that's needed.

**Comment by FaithLV** [comment]
@Joshua-Ashton I'm using VSCode which defaults meson builder folder to `builddir`

**Comment by Joshua-Ashton** [comment]
You shouldn't use that intergration because of the terrible default dir and how painful it is to specify definitions and options.

The Meson intergration for VSCode is also horifically broken in general last time I used it.

**Comment by DadSchoorse** [comment]
>Why builddir? Why are you calling your build folder that when there are plenty of other options in the .gitignore already?
>
>All the DLLs should also be built inside the meson build folder so I don't see why that's needed. 

`builddir` is what meson recommends nowadays.
https://github.com/mesonbuild/meson/commit/f3be687cbbfd1ff25c7ec4ffe8ba4adfee9a6579

**Pull request closed without merging**
