### PR TITLE
Fix Persona 3 Reload performance

### PR DESCRIPTION
**Pull request by HansKristian-Work**
DXIL PR: https://github.com/HansKristian-Work/dxil-spirv/pull/183

Root cause was some very broken shaders that caused **horrendous** spilling. Apparently AMD native managed to optimize through it, which is likely what caused Windows to run much faster. DXC apparently fails to optimize some alloca() -> store -> load patterns properly, so we have to do it :(

So far I've yet to see a section below 60 fps on Deck with RT off / medium shadows, but I haven't tested exhaustively of course ... Tartarus blue lights and Velvet room both hit 60 for me easily now at least. Point lights had associated shaders that triggered the massive slowdown.

Before:

gamescope_2024-02-05_23-22-49

After:

gamescope_2024-02-05_23-24-45

Settings:

gamescope_2024-02-05_23-24-59

(game throttles itself to 30 on settings)

Performance on my RX 7600 was boosted with 40% in 4k on the Tartarus light.

This opt also affects a bunch of other games to various degrees, but it's unsure how much perf is improved. For our testers to go through to make sure there are no regressions. Anything not pinned to Proton Stable is of particular interest here.

- BF2042
- Death Stranding Directors Cut
- Elden Ring
- F1 2021
- F1 2022
- Forza Horizon 5
- Guardians of the Galaxy
- Horizon Zero Dawn
- Halo Infinite
- RE2
- RE8
- Alan Wake 2
- CP77
- Armored Core 6
- Dirt 5
- Forspoken
- Immortals of Aveum
- Jedi Survivor
- Lords of the Fallen
- P3R (duh)
- RE4
- Remnant II
- Starfield
- SF6
- The Last of Us Part 1
- Uncharted
- Witcher 3
- WRC G

### CODE REVIEW

**Comment by Lacroixs** [comment]
Huh, interesting. Is there a way for us to test this out? Esp curious about how performance is on the Steam Deck now

**Comment by HansKristian-Work** [comment]
It should hit Proton Experimental bleeding edge within an hour. It should hit a non-bleeding edge build eventually, but I don't have exact timeline on that.

**Comment by Lacroixs** [comment]
Thank you for your hard work, I have almost no knowledge on this stuff so i am glad you guys work so diligently on this.

**Comment by Logge1002** [comment]
If you change the fps to 60 the menus are 60 as well. Hope with this the steam deck performance will finally be up to snuff. Because it's otherwise extremely enjoyable on the deck!

**Comment by runar-work** [comment]
Testing with RX 7600 and (mostly) Mesa 23.3.5 on 6.7.3-arch1-2. Didn't see any signs of regressions while testing in: 
- Halo Infinite
- Starfield
- TLOU1
- F1 2021

I had to use latest Mesa main for F1 2021 to avoid GPU hangs, but had no issues with that version.

**Comment by Lacroixs** [comment]
Issue with Monad area in p3r, drops are horrid down to 20, the lighting is quite intense so I think that might be the case.

**Comment by HansKristian-Work** [comment]
> Issue with Monad area in p3r, drops are horrid down to 20, the lighting is quite intense so I think that might be the case.

And that's with these changes? Are there save files for anyone to repro?

**Comment by simifor** [comment]
Didn't notice a measurable difference in Guardians of the Galaxy. Tested on a RX 6600, Mesa 23.3.5 on 6.7.3-arch1-2.

**Comment by PiTTi616** [comment]
Weird. I still have the same issues in windows with a amd processor and igpu. Any idea why this happens?

**Comment by runar-work** [comment]
A few more tests:
- Resident Evil 4
- F1 22
- Lords of the Fallen

I tested Resident Evil 4 on Deck with main OS.

**Comment by runar-work** [comment]
Last ones for today:
- Remnant II
- Death Stranding

**Comment by PenguinRap** [comment]
Working great with Daily Life/Tartarus! (Medium Shadows/100% Resolution/RT OFF)
However I did see drops to the 30/40's during the 1st Full Moon boss area. Not sure if due to the shaders or not but that was the first instance of seeing some major drops since this fix.
Thanks again for all the hard work so far!

**Comment by HansKristian-Work** [comment]
We've root caused why Velvet Room and some other places drops below 60.

**Comment by runar-work** [comment]
I've tested Elden Ring (both on desktop and deck) and Cyberpunk and didn't see any issues there either.

**Comment by Logge1002** [comment]
Any improvements on stranger of paradise with this? Ran horrible on steam deck before but maybe someone could check that?

**Comment by mbriar** [comment]
@Logge1002 definitely not with this, SoP uses d3d11.

**Comment by Blisto91** [comment]
Checked a few with no issues found:
Forza Horizon 5
Witcher 3
Forspoken

Tested on a RX 6800 with a couple of days old mesa main

**Comment by StoryArts** [comment]
> We've root caused why Velvet Room and some other places drops below 60. The game relies on very inefficient use of GS to render shadow maps.
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/6260#note_2272979
> 
> I had another place in floor 22 where I dipped to about 51 fps, but with the proposed "fix" I hit 60 fps.

Is there a way to use this fix or is it coming to proton experimental (bleeding-edge)?

**Comment by HansKristian-Work** [comment]
> > We've root caused why Velvet Room and some other places drops below 60. The game relies on very inefficient use of GS to render shadow maps.
> > https://gitlab.freedesktop.org/mesa/mesa/-/issues/6260#note_2272979
> > I had another place in floor 22 where I dipped to about 51 fps, but with the proposed "fix" I hit 60 fps.
> 
> Is there a way to use this fix or is it coming to proton experimental (bleeding-edge)?

you can experiment with it by using launch options `RADV_DEBUG=nongg %command%`. A proper fix needs Mesa work though.

**Comment by StoryArts** [comment]
> > > We've root caused why Velvet Room and some other places drops below 60. The game relies on very inefficient use of GS to render shadow maps.
> > > https://gitlab.freedesktop.org/mesa/mesa/-/issues/6260#note_2272979
> > > I had another place in floor 22 where I dipped to about 51 fps, but with the proposed "fix" I hit 60 fps.
> > 
> > 
> > Is there a way to use this fix or is it coming to proton experimental (bleeding-edge)?
> 
> you can experiment with it by using launch options `RADV_DEBUG=nongg %command%`. Expect some shader compilation stutter on first run however. A proper fix needs Mesa work though, this isn't really something we can work around in vkd3d-proton.

Ah I see, I'm going to assume a fix like this is probably going to come after a quite a bit of time. Disappointingly, the windows version has shader compilation stutter as well so I'd probably wait just for the pre-complied shaders on SD.

**Comment by HansKristian-Work** [comment]
There's a pending Mesa MR to resolve this, I'll keep an eye out for when it lands on devices.

**Comment by Lacroixs** [comment]
@HansKristian-Work does this mesa mr update need to be manually applied?

**Comment by HansKristian-Work** [comment]
> @HansKristian-Work does this mesa mr update need to be manually applied?

For Deck, you should just wait until an update is shipped. The mesa MR basically applies the nongg hack only for the troublesome geometry shaders, where nongg is just a very crude hack to get the same effect (but all normal vertex shading is a bit slower as a result).

**Comment by Lacroixs** [comment]
> > @HansKristian-Work does this mesa mr update need to be manually applied?
> 
> For Deck, you should just wait until an update is shipped. The mesa MR basically applies the nongg hack only for the troublesome geometry shaders, where nongg is just a very crude hack to get the same effect (but all normal vertex shading is a bit slower as a result).

Oh I see. I assume we can expect this in a week or so? Hoping this fixes more than just one game though, also all across the board should be benefited from this

**Comment by Logge1002** [comment]
Would Judgment improve with that hotfix?

**Comment by runar-work** [comment]
More tests without any noticeable issues: 
- Jedi Survivor
- Resident Evil 2 (on Deck)

On 6.7.4-arch1-1:
- Resident Evil Village
- Horizon Zero Dawn
- Armored Core 6

**Comment by HansKristian-Work** [comment]
> > > @HansKristian-Work does this mesa mr update need to be manually applied?
> > 
> > 
> > For Deck, you should just wait until an update is shipped. The mesa MR basically applies the nongg hack only for the troublesome geometry shaders, where nongg is just a very crude hack to get the same effect (but all normal vertex shading is a bit slower as a result).
> 
> Oh I see. I assume we can expect this in a week or so? Hoping this fixes more than just one game though, also all across the board should be benefited from this

Mesa fix is live on preview branch.

**Comment by Lacroixs** [comment]
Thank you

**Comment by runar-work** [comment]
Also tested these without any noticeable difference or issues:
- Uncharted 4
- Immortals of Aveum
- SF6
- Dirt 5

I had some initial launch issues with Uncharted, but I wasn't able to reproduce it later, so it seems to have been unrelated.

**Pull request merged**
