### PR TITLE
Return E_INVALIDARG for SampleDesc.Count == 0

### PR DESCRIPTION
**Pull request by conor42**

### CODE REVIEW

**Comment by doitsujin** [comment]
didn't we run into an app that required this to succeed?

**Comment by conor42** [comment]
> 
> 
> didn't we run into an app that required this to succeed?

The reverted patch was for Psychonaughts 2, but it turns out to run better if the call fails, at least on an RX580/RADV. Was there something else?

**Comment by Joshua-Ashton** [comment]
Windows doesnt return E_INVALIDARG though, not in this case. I have an apitrace that shows a call with it succeeding on native Windows. Maybe there is something else at play?

**Comment by Joshua-Ashton** [comment]
inb4 this is an amd vs nv difference or something... The trace was recorded on NV

**Comment by conor42** [comment]
> 
> 
> inb4 this is an amd vs nv difference or something... The trace was recorded on NV

Looks like it. I tested again in Windows + RX580, definitely E_INVALIDARG.

The game in DX12 mode has issues with excessive vram usage and needing to be run at low graphics settings. It wouldn't run at all on my system at default settings with upstream Wine + vkd3d-proton until I made this change. After that it did great.

**Comment by Joshua-Ashton** [comment]
If its causing issues then I have no problem reverting this.

**Comment by conor42** [comment]
Maybe the game should be tested on nvidia to make sure there isn't any hardware dependency weirdness going on

**Comment by conor42** [comment]
Also if the test produces a different result on nvidia it will need a bug_if, or we could just omit testing entirely. Btw I stumbled upon this problem when adding a test to upstream vkd3d, where they're generally needed pass review.

**Comment by Joshua-Ashton** [comment]
I will test this on NV today.

**Comment by Joshua-Ashton** [comment]
Hm, test seems to pass fine here on NV...

**Pull request merged**
