### PR TITLE
Implement workarounds for Invariant position

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Introduces a scheme where we can enable Invariant vertex positions, either:

- Globally
- Per-game
- Per-shader (ye, no)

After many trials and tribulations, make the choice to enable Invariant by default.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
> You might want to consider "Monster Hunter World" too.

We should add all games which are known to be broken. Is it just MHW?

**Comment by hakzsam** [comment]
AFAIK, yes. At least, RADV has a similar workaround for MHW DX12.

**Comment by Oschowa** [comment]
RADV also has the same workaround applied for Shadow of the Tomb Raider dx11/12.

**Comment by CME42** [comment]
Life is Strange True Colors should also be added: Siren-Win64-Shipping.exe

**Pull request merged**
