### PR TITLE
Update setup_vkd3d_proton.sh

### PR DESCRIPTION
**Pull request by Ahmed-E-86**
Add an optional WINE variable that can be used with custom wine builds.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Needs Signed-off-by line. `git commit --amend -s` to do this automatically.

**Comment by doitsujin** [comment]
As mentioned on the DXVK PR, I don't see a good reason to do this when `PATH` and `WINELOADER` exist.

**Comment by Ahmed-E-86** [comment]
I tried to use `WINELOADER` the same way I use `WINE`, and I end up with an error message. Could you explain how it can be used?

**Comment by IroAlexis** [comment]
You can use $PATH variable like this `PATH=/path/to/wine-dir/bin:$PATH ./setup_vkd3d_proton.sh install`

**Comment by Ahmed-E-86** [comment]
> You can use $PATH variable like this `PATH=/path/to/wine-dir/bin:$PATH ./setup_vkd3d_proton.sh install`

No, this does not work as it should be, because PATH does not define the location of wine64, and wineboot. Also, Proton and Proton-GE do not have wineboot binary, so in order to execute wineboot, you need to execute it as `wine wineboot` instead of just `wineboot`.

**Comment by Ahmed-E-86** [comment]
> You can use $PATH variable like this `PATH=/path/to/wine-dir/bin:$PATH ./setup_vkd3d_proton.sh install`

Thanks for your comment. $PATH will work fine after `wineboot="wineboot"` changed to `wineboot="wine wineboot"`, otherwise wineboot of wine installed on the OS will be used instead, especially with Proton and Proton-GE, so a small change needs to be made.

**Pull request closed without merging**
