### PR TITLE
profile: Update for SM 6.7.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Draft for now since profiles solution generator is broken.

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
I believe the issue is that the profiles file was not correct and the script reported valid errors. I improved one error message (https://github.com/KhronosGroup/Vulkan-Profiles/pull/611) so that it's clearer how the resolve the issue. (Here a missing extension declaration)

I largely spawm (sorry about that! ^_^) the reported issue with information and the fixed profiles file.

**Comment by HansKristian-Work** [comment]
@christophe-lunarg As mentioned on https://github.com/KhronosGroup/Vulkan-Profiles/issues/609#issuecomment-1945715236 I'm still unable to build the profile with updated .json and profiles repo.

**Comment by HansKristian-Work** [comment]
Nvm, the build script was pointing to a stale header.

**Comment by HansKristian-Work** [comment]
Still some jank though. VK_KHR_maintenance5 references just disappeared, and I cannot see shader_quad_control or any of those extensions in the markdown output.

**Comment by christophe-lunarg** [comment]
> Still some jank though. VK_KHR_maintenance5 references just disappeared, and I cannot see shader_quad_control or any of those extensions in the markdown output.

Ah, true... investigating...

**Comment by christophe-lunarg** [comment]
I fixed I got a fix: https://github.com/KhronosGroup/Vulkan-Profiles/pull/615

A generated file:
[PROFILES_TEST.md](https://github.com/HansKristian-Work/vkd3d-proton/files/14298871/PROFILES_TEST.md)

A dummy problem, sorry about that! :/

**Comment by christophe-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Profiles/pull/615 was merged, hopefully you should be good to go!

**Comment by HansKristian-Work** [comment]
Yes, now it works. Thanks for your help!

**Review by doitsujin — APPROVED** [review]

**Pull request merged**
