### PR TITLE
Add missing D3D12 constants

### PR DESCRIPTION
**Pull request by expipiplus1**
I sorted the constants by name in the first commit to make any
differences more apparent in the second commit

- Correct the spelling of D3D12_RAYTRACING_INSTANCE_DESCS_BYTE_ALIGNMENT (previously it was D3D12_RAYTRACING_INSTANCE_DESC_BYTE_ALIGNMENT)

- Correct type of D3D12_VIEWPORT_BOUNDS_MIN from UINT to INT

### CODE REVIEW

**Comment by mbriar** [comment]
Is this the same as https://github.com/HansKristian-Work/vkd3d-proton/issues/1460 for the Demo? Maybe more shader hashes need to be added to the quirk list..

**Comment by doitsujin** [comment]
what do we need these for exactly?

**Comment by expipiplus1** [comment]
These are useful for compiling D2D12 programs using these constants against the headers in this repo

They were taken from the IDL files in https://github.com/microsoft/DirectX-Headers which are in turn sourced from the DX12 hardware specs

**Comment by HansKristian-Work** [comment]
@doitsujin are there any concerns merging this? Seems okay to me.

**Comment by expipiplus1** [comment]
I added in a missing typedef and a couple of other macros present in the official dx12 headers.

It does seem a little weird to be adding these manually piecemeal, is the API now similar enough to DX12 to encode these headers as some fixup over the Microsoft headers?

**Comment by HansKristian-Work** [comment]
The upstream headers will only ever build on MSVC and generally we add IDL as needed. There hasn't been much use for external projects using our headers so far.

**Review by doitsujin — APPROVED** [review]

**Comment by expipiplus1** [comment]
Gotcha, thanks!

**Pull request merged**
