### PR TITLE
Mark version 2.0.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Signed-off-by: Hans-Kristian Arntzen <post@arntzen-software.no>

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Testing on 1660ti:
- Test suite 0 failures
- Death Stranding
- Horizon Zero Dawn
- RE2
- DMC5
- Metro
- SOTTR does not boot (not a regression in vkd3d-proton, ran into this a long time ago where I tried much older vkd3d-proton versions, likely NV bug on more recent drivers. No relevant validation errors, no relevant trace messages)

**Comment by doitsujin** [comment]
Monster Hunter World no longer works. This is a regression that needs to be fixed before we tag anything.

**Review by doitsujin — APPROVED** [review]
Based on my testing: Good to go.

**Comment by HansKristian-Work** [comment]
No change after last changes on 1660ti, good to go on my end.

**Pull request merged**
